// For use with the fast_noise() function.

enum noise_type:
    noise_type_opensimplex2
    noise_type_opensimplex2s
    noise_type_cellular
    noise_type_perlin
    noise_type_value_cubic
    noise_type_value

enum fractal_type:
    fractal_type_none
    fractal_type_fbm
    fractal_type_ridged
    fractal_type_pingpong
    fractal_type_domain_warp_progressive
    fractal_type_domain_warp_independent
